# **Numpy**

Numpy é uma das bibliotecas mais importantes em Python para computação científica e análise de dados. Ela fornece um poderoso objeto de matriz multidimensional, bem como funções para manipular e trabalhar com essas matrizes. O numpy é um pacote fundamental para cientistas de dados, engenheiros e pesquisadores em diversas áreas de pesquisa.

NumPy , abreviação de **Numerical Python**, tem sido a pedra angular da computação numérica em Python. Ele fornece as estruturas de dados, algoritmos e cola de biblioteca necessária para a maioria das aplicações científicas envolvendo dados numéricos em Python.

# **Criando um array:**

O numpy é baseado em matrizes, que são semelhantes às listas do Python, mas com a diferença de que todas as matrizes devem conter elementos do mesmo tipo. A forma mais simples de criar uma matriz é usando a função numpy.array():



In [ ]:
##importando a biblioteca
import numpy as np

In [ ]:
# criando um array de uma dimensão
array1d = np.array([1, 2, 3, 4, 5])
array1d

array([1, 2, 3, 4, 5])

In [ ]:
# criando um array de duas dimensões
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# criando um array com valores aleatórios
array_aleatorio = np.random.rand(3, 3) # array 3x3 com valores aleatórios
array_aleatorio

array([[0.55575051, 0.95276234, 0.33656961],
       [0.52715719, 0.43551021, 0.12808872],
       [0.68804636, 0.44162678, 0.17311369]])

# **Indexação**

A indexação em matrizes numpy é muito semelhante à indexação em listas do Python, com a diferença de que podemos usar várias dimensões para indexar uma matriz multidimensional. Para acessar um elemento de uma matriz, usamos colchetes '[ ]' e especificamos os índices:

In [ ]:
# acessando um elemento de um array
print(array1d[0]) # 1

1


In [ ]:
# acessando um elemento de um array 2D
print(array2d[1, 2]) # 6


6


# **Slicing**

Slicing em matrizes numpy é muito semelhante ao slicing em listas do Python. Podemos acessar uma submatriz de uma matriz especificando o intervalo de índices que queremos:


In [ ]:
# criando um array de duas dimensões
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d

In [ ]:
##É uma matriz 2d
array2d.shape

In [ ]:
# acessando uma submatriz
##vamos pegar a matriz até a segunda linha e só as ultimas 2 colunas
print(array2d[:2, 1:]) # [[2, 3], [5, 6]]

[[2 3]
 [5 6]]


# **Operações básicas:**

O numpy fornece muitas funções e métodos para realizar operações em matrizes. Algumas operações básicas incluem:


In [ ]:
##1D
array1d

array([1, 2, 3, 4, 5])

In [ ]:
# somando elementos de um array
print(np.sum(array1d)) # 15

15


In [ ]:
# somando elementos de um array 2D
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.sum(array2d)) # 45

45


In [ ]:
# encontrando o valor máximo de um array
array1d

array([1, 2, 3, 4, 5])

In [ ]:
print(np.max(array1d)) # 5

5


In [ ]:
# encontrando o valor mínimo de um array
print(np.min(array1d)) # 1

1


In [ ]:
# encontrando a média de um array
print(np.mean(array1d)) # 3.0

3.0


# **Manipulando arrays:**

O numpy fornece muitas funções para manipular matrizes, incluindo reshape(), transpose(), concatenate() e muitas outras. Aqui estão alguns exemplos:

In [ ]:
# mudando a forma de um array
array1d = np.array([1, 2, 3, 4, 5, 6])
array1d

array([1, 2, 3, 4, 5, 6])

In [ ]:
# mudando a forma de um array
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = array1d.reshape(2, 3) ##duaslinhas e 3 colunas
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
### transpondo um array
array2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# concatenando arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array_concatenado = np.concatenate((array1, array2))
array_concatenado

array([1, 2, 3, 4, 5, 6])

In [ ]:
# empilhando arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array_empilhado = np.vstack((array1, array2))
array_empilhado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])